/* Generated by JTB 1.4.11 */
package medit.BPP.syntaxtree;

import medit.BPP.visitor.IRetArguVisitor;
import medit.BPP.visitor.IRetVisitor;
import medit.BPP.visitor.IVoidArguVisitor;
import medit.BPP.visitor.IVoidVisitor;

public interface INode extends java.io.Serializable {

	/** The OS line separator */
	public static final String LS = System.getProperty("line.separator");

	public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu);

	public <R> R accept(final IRetVisitor<R> vis);

	public <A> void accept(final IVoidArguVisitor<A> vis, final A argu);

	public void accept(final IVoidVisitor vis);

}
