/* Generated by JTB 1.4.11 */
package medit.BPP.syntaxtree;

import medit.BPP.visitor.IRetArguVisitor;
import medit.BPP.visitor.IRetVisitor;
import medit.BPP.visitor.IVoidArguVisitor;
import medit.BPP.visitor.IVoidVisitor;

public class JavaStaticMethods implements INode {

	private static final long serialVersionUID = 1411L;

	public NodeToken f0;

	public NodeList f1;

	public NodeToken f2;

	public MathExpression f3;

	public NodeListOptional f4;

	public NodeToken f5;

	public NodeToken f6;

	public JavaStaticMethods(final NodeToken n0, final NodeList n1, final NodeToken n2, final MathExpression n3,
			final NodeListOptional n4, final NodeToken n5, final NodeToken n6) {
		this.f0 = n0;
		this.f1 = n1;
		this.f2 = n2;
		this.f3 = n3;
		this.f4 = n4;
		this.f5 = n5;
		this.f6 = n6;
	}

	@Override
	public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
		return vis.visit(this, argu);
	}

	@Override
	public <R> R accept(final IRetVisitor<R> vis) {
		return vis.visit(this);
	}

	@Override
	public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
		vis.visit(this, argu);
	}

	@Override
	public void accept(final IVoidVisitor vis) {
		vis.visit(this);
	}

}
