/* Generated by JTB 1.4.11 */
package medit.BPP.syntaxtree;

import medit.BPP.visitor.IRetArguVisitor;
import medit.BPP.visitor.IRetVisitor;
import medit.BPP.visitor.IVoidArguVisitor;
import medit.BPP.visitor.IVoidVisitor;

public class NodeChoice implements INode {

	private static final long serialVersionUID = 1411L;

	public INode choice;

	public int total;

	public int which;

	public NodeChoice(final INode node) {
		this(node, -1, -1);
	}

	public NodeChoice(final INode node, final int whichChoice, final int totalChoices) {
		this.choice = node;
		this.which = whichChoice;
		this.total = totalChoices;
	}

	@Override
	public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
		return this.choice.accept(vis, argu);
	}

	@Override
	public <R> R accept(final IRetVisitor<R> vis) {
		return this.choice.accept(vis);
	}

	@Override
	public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
		this.choice.accept(vis, argu);
	}

	@Override
	public void accept(final IVoidVisitor vis) {
		this.choice.accept(vis);
	}

}
