/* Generated by JTB 1.4.11 */
package medit.BPP.syntaxtree;

import medit.BPP.visitor.IRetArguVisitor;
import medit.BPP.visitor.IRetVisitor;
import medit.BPP.visitor.IVoidArguVisitor;
import medit.BPP.visitor.IVoidVisitor;

public class VariableAssign implements INode {

	private static final long serialVersionUID = 1411L;

	public VariableName f0;

	public NodeToken f1;

	public MathExpression f2;

	public NodeToken f3;

	public VariableAssign(final VariableName n0, final NodeToken n1, final MathExpression n2, final NodeToken n3) {
		this.f0 = n0;
		this.f1 = n1;
		this.f2 = n2;
		this.f3 = n3;
	}

	@Override
	public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
		return vis.visit(this, argu);
	}

	@Override
	public <R> R accept(final IRetVisitor<R> vis) {
		return vis.visit(this);
	}

	@Override
	public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
		vis.visit(this, argu);
	}

	@Override
	public void accept(final IVoidVisitor vis) {
		vis.visit(this);
	}

}
