/* Generated by JTB 1.4.11 */
package medit.BPP.syntaxtree;

import medit.BPP.visitor.*;

public class VariableDeclaration implements INode {

  public NodeToken f0;

  public VariableName f1;

  public NodeToken f2;

  public MathExpression f3;

  public NodeToken f4;

  private static final long serialVersionUID = 1411L;

  public VariableDeclaration(final NodeToken n0, final VariableName n1, final NodeToken n2, final MathExpression n3, final NodeToken n4) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
  }

  @Override
  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  @Override
  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  @Override
  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  @Override
  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
