/* Generated by JTB 1.4.11 */
package medit.BPP.visitor;

import medit.BPP.syntaxtree.AdditiveExpression;
import medit.BPP.syntaxtree.IfExpression;
import medit.BPP.syntaxtree.JavaStaticMethods;
import medit.BPP.syntaxtree.MathExpression;
import medit.BPP.syntaxtree.MultiplicativeExpression;
import medit.BPP.syntaxtree.NodeChoice;
import medit.BPP.syntaxtree.NodeList;
import medit.BPP.syntaxtree.NodeListOptional;
import medit.BPP.syntaxtree.NodeOptional;
import medit.BPP.syntaxtree.NodeSequence;
import medit.BPP.syntaxtree.NodeTCF;
import medit.BPP.syntaxtree.NodeToken;
import medit.BPP.syntaxtree.RelationalEqualityExpression;
import medit.BPP.syntaxtree.RelationalExprssion;
import medit.BPP.syntaxtree.RelationalGreaterExpression;
import medit.BPP.syntaxtree.RelationalLessExpression;
import medit.BPP.syntaxtree.Require;
import medit.BPP.syntaxtree.Start;
import medit.BPP.syntaxtree.StatementExpression;
import medit.BPP.syntaxtree.UnaryExpression;
import medit.BPP.syntaxtree.UnaryRelational;
import medit.BPP.syntaxtree.VariableAssign;
import medit.BPP.syntaxtree.VariableDeclaration;
import medit.BPP.syntaxtree.VariableName;
import medit.BPP.syntaxtree.WhileExpression;

public interface IVoidVisitor {

	public void visit(final AdditiveExpression n);

	public void visit(final IfExpression n);

	public void visit(final JavaStaticMethods n);

	public void visit(final MathExpression n);

	public void visit(final MultiplicativeExpression n);

	public void visit(final NodeChoice n);

	public void visit(final NodeList n);

	public void visit(final NodeListOptional n);

	public void visit(final NodeOptional n);

	public void visit(final NodeSequence n);

	public void visit(final NodeTCF n);

	public void visit(final NodeToken n);

	public void visit(final RelationalEqualityExpression n);

	public void visit(final RelationalExprssion n);

	public void visit(final RelationalGreaterExpression n);

	public void visit(final RelationalLessExpression n);

	public void visit(final Require n);

	public void visit(final Start n);

	public void visit(final StatementExpression n);

	public void visit(final UnaryExpression n);

	public void visit(final UnaryRelational n);

	public void visit(final VariableAssign n);

	public void visit(final VariableDeclaration n);

	public void visit(final VariableName n);

	public void visit(final WhileExpression n);

}
