/* Generated By:JavaCC: Do not edit this line. BPPConstants.java */
package medit.BPP;

/**
 * Token literal values and constants. Generated by
 * org.javacc.parser.OtherFilesGen#start()
 */
public interface BPPConstants {

	/** RegularExpression Id. */
	int ASSIGN = 25;
	/** RegularExpression Id. */
	int COLON = 13;
	/** RegularExpression Id. */
	int DEF = 11;
	/** Lexical state. */
	int DEFAULT = 0;
	/** RegularExpression Id. */
	int DIGIT = 29;
	/** RegularExpression Id. */
	int DIV = 23;
	/** RegularExpression Id. */
	int DO = 9;
	/** RegularExpression Id. */
	int DOT = 12;
	/** End of File. */
	int EOF = 0;
	/** RegularExpression Id. */
	int EQ = 14;
	/** RegularExpression Id. */
	int GE = 17;
	/** RegularExpression Id. */
	int GT = 15;
	/** RegularExpression Id. */
	int IDENTIFIER = 27;
	/** RegularExpression Id. */
	int IF = 7;
	/** RegularExpression Id. */
	int INTEGER_LITERAL = 26;
	/** RegularExpression Id. */
	int LE = 18;
	/** RegularExpression Id. */
	int LETTER = 28;
	/** RegularExpression Id. */
	int LT = 16;
	/** RegularExpression Id. */
	int MINUS = 21;
	/** RegularExpression Id. */
	int MOD = 24;
	/** RegularExpression Id. */
	int MUL = 22;
	/** RegularExpression Id. */
	int NE = 19;
	/** RegularExpression Id. */
	int PLUS = 20;
	/** RegularExpression Id. */
	int REQUERE = 6;
	/** RegularExpression Id. */
	int STOP = 10;

	/** Literal token values. */
	String[] tokenImage = { "<EOF>", "\" \"", "\"\\t\"", "\"\\n\"", "\"\\r\"", "<token of kind 5>", "\"with\"",
			"\"if\"", "\"while\"", "\"begin\"", "\"end\"", "\"var\"", "\".\"", "\":\"", "\"==\"", "\">\"", "\"<\"",
			"\">=\"", "\"<=\"", "\"!=\"", "\"+\"", "\"-\"", "\"*\"", "\"/\"", "\"%\"", "\"=\"", "<INTEGER_LITERAL>",
			"<IDENTIFIER>", "<LETTER>", "<DIGIT>", "\"(\"", "\")\"", "\",\"", };

	/** RegularExpression Id. */
	int WHILE = 8;

}
